name: build-dbot-service
description: "Build DBot Service and push container"
inputs:
  registry:
    description: "The image registry to push to"
    required: true
  username:
    description: "The username of the user allowed to push images to ghcr"
    required: true
  password:
    description: "The password of the user allowed to push images ghcr"
    required: true
  image_name:
    description: "The name of the image to push"
    required: true

runs:
    using: "composite"
    steps:
      - name: Login to container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Compile protobuf
        shell: pwsh
        run: ./compile_protobuf.ps1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
