
name: DBot Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-dbot-intent-service:
    uses: "./.github/workflows/build-service-workflow.yml"
    with:
      image_name: dbot-intent-service
      context: dbot-intent-service
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  test-dbot-intent-service:
    needs: build-dbot-intent-service
    uses: "./.github/workflows/test-service-workflow.yml"
    with:
      image_name: dbot-intent-service
      workdir: /dbot/intent_service
      test_report_name: dbot_intent_service.xml
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
