name: Test DBot Service

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      workdir:
        required: true
        type: string
      test_report_name:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  test-dbot-service:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/donaldm/mbot-neo-dbot/${{ image_name }}:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test
        uses: "./.github/templates/test-dbot-service"
        with:
          workdir: ${{ input.workdir }}
          test_report_name: ${{ input.test_report_name }}
